; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = pico2_debug

[env:pico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower
lib_deps = mcp_can@1.5.1
;debug_tool = cmsis-dap
monitor_speed = 115200
custom_flash_link_target = runtime
build_src_filter =
    +<*>
    -<boot_update/>
build_flags =
    -DCONTROLLER_DEBUG=0
    -DLOG_LEVEL=2
    -DFW_LINK_TARGET_SLOT=0
    -I$PROJECT_DIR/include  ; Add include directory to library search path
extra_scripts = 
    pre:scripts/generate_version.py
    pre:scripts/add_flash_nvm_guard.py
    post:scripts/generate_joint_config.py

[env:pico2_debug]
extends = env:pico2
build_flags =
    -DCONTROLLER_DEBUG=1 
    -DLOG_LEVEL=3
    -DFW_LINK_TARGET_SLOT=0
    -I$PROJECT_DIR/include

[env:pico2_boot_update]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
custom_flash_link_target = boot_update
build_src_filter =
    -<*>
    +<boot_update/>
build_flags =
    -DNO_USB
    -DLOG_LEVEL=0
    -DFW_LINK_TARGET_SLOT=0
    -I$PROJECT_DIR/include
extra_scripts =
    pre:scripts/generate_version.py
    pre:scripts/add_flash_nvm_guard.py

[env:pico2_boot_update_debug]
extends = env:pico2_boot_update
build_flags =
    -DNO_USB
    -DLOG_LEVEL=3
    -DFW_LINK_TARGET_SLOT=0
    -I$PROJECT_DIR/include

[env:pico2_slot_a]
extends = env:pico2
custom_flash_link_target = slot_a
build_flags =
    -DCONTROLLER_DEBUG=0
    -DLOG_LEVEL=2
    -DFW_LINK_TARGET_SLOT=1
    -I$PROJECT_DIR/include

[env:pico2_slot_a_debug]
extends = env:pico2_slot_a
build_flags =
    -DCONTROLLER_DEBUG=1
    -DLOG_LEVEL=3
    -DFW_LINK_TARGET_SLOT=1
    -I$PROJECT_DIR/include

[env:pico2_slot_b]
extends = env:pico2
custom_flash_link_target = slot_b
build_flags =
    -DCONTROLLER_DEBUG=0
    -DLOG_LEVEL=2
    -DFW_LINK_TARGET_SLOT=2
    -I$PROJECT_DIR/include

[env:pico2_slot_b_debug]
extends = env:pico2_slot_b
build_flags =
    -DCONTROLLER_DEBUG=1
    -DLOG_LEVEL=3
    -DFW_LINK_TARGET_SLOT=2
    -I$PROJECT_DIR/include
