M48
; DRILL file {KiCad 7.0.7} date 2025 December 10, Wednesday 14:06:49
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-12-10T14:06:49+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0945
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1280
%
G90
G05
T1
X4.8656Y-5.8583
X5.0565Y-5.8583
T2
X4.8537Y-5.9776
X5.0683Y-5.9776
T3
X4.685Y-1.5039
T4
X3.0543Y-3.1393
X3.0543Y-3.6393
T0
M30
